### ISSUE TITLE
#Error

### ISSUE THREAD

**Issue by gangubai** [shubhamjai9/Emotion-Based-Counsellor-Bot#1]
python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 11, in <module>
    nlp = spacy.load('en')
  File "/home/research_centre_gpu/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/research_centre_gpu/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Even I tried with python2

**Comment by fdemir25** [comment]
[8776:5568:1013/191630.433:ERROR:device_event_log_impl.cc(208)] [19:16:30.433] Bluetooth: bluetooth_adapter_winrt.cc:1164 RequestRadioAccessAsync failed: RadioAccessStatus::DeniedBySystemWill not be able to change radio power.
